"""tabla V3

Revision ID: 07011b5ecc31
Revises: 
Create Date: 2025-11-14 05:35:32.365145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07011b5ecc31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recetas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('recetaPorcion', sa.Enum('POR_HACER', 'HACIENDO', 'FINALIZADO', name='porcionEnum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recetas')
    # ### end Alembic commands ###
