"""tablas

Revision ID: 3aa2571d5095
Revises: 
Create Date: 2025-11-17 15:08:05.135008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa2571d5095'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('recetas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('porcion', sa.Enum('FAMILIAR', 'MEDIANO', 'PERSONAL', name='enumporcion'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('preparaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('recetas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recetas_id'], ['recetas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('recetas_ingredientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cantidad', sa.String(length=50), nullable=False),
    sa.Column('recetas_id', sa.Integer(), nullable=False),
    sa.Column('ingredientes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredientes_id'], ['ingredientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recetas_id'], ['recetas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recetas_ingredientes')
    op.drop_table('preparaciones')
    op.drop_table('recetas')
    op.drop_table('ingredientes')
    # ### end Alembic commands ###
