"""tabla V4

Revision ID: 48d9350cdb3e
Revises: 07011b5ecc31
Create Date: 2025-11-14 05:37:02.516641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48d9350cdb3e'
down_revision = '07011b5ecc31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('porcion', sa.Enum('POR_HACER', 'HACIENDO', 'FINALIZADO', name='enumestado'), nullable=True))
        batch_op.drop_column('recetaPorcion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recetaPorcion', mysql.ENUM('POR_HACER', 'HACIENDO', 'FINALIZADO'), nullable=True))
        batch_op.drop_column('porcion')

    # ### end Alembic commands ###
