"""modificando nombre de columnas FK

Revision ID: 57961ae96e6f
Revises: d60783c8de5a
Create Date: 2025-11-16 06:36:26.478695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57961ae96e6f'
down_revision = 'd60783c8de5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas_ingredientes', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('recetas_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('ingredientes_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas_ingredientes', schema=None) as batch_op:
        batch_op.alter_column('ingredientes_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('recetas_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('cantidad',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
