"""agregar campo cantidad

Revision ID: d60783c8de5a
Revises: 44a6aa23dd46
Create Date: 2025-11-16 06:28:56.823252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60783c8de5a'
down_revision = '44a6aa23dd46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas_ingredientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas_ingredientes', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
