"""tabla preparacion receta_ingrediente

Revision ID: dead8054fbaa
Revises: 48d9350cdb3e
Create Date: 2025-11-14 06:05:41.823907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dead8054fbaa'
down_revision = '48d9350cdb3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preparaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('recetas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recetas_id'], ['recetas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('recetas_ingredientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recetas_id', sa.Integer(), nullable=True),
    sa.Column('ingredientes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredientes_id'], ['ingredientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recetas_id'], ['recetas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recetas_ingredientes')
    op.drop_table('preparaciones')
    # ### end Alembic commands ###
