"""cambiando enum

Revision ID: e426883d2428
Revises: ef6428bf9124
Create Date: 2025-11-14 18:51:50.636988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e426883d2428'
down_revision = 'ef6428bf9124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.alter_column('porcion',
               existing_type=mysql.ENUM('POR_HACER', 'HACIENDO', 'FINALIZADO'),
               type_=sa.Enum('FAMILIAR', 'MEDIANO', 'PERSONAL', name='enumestado'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.alter_column('porcion',
               existing_type=sa.Enum('FAMILIAR', 'MEDIANO', 'PERSONAL', name='enumestado'),
               type_=mysql.ENUM('POR_HACER', 'HACIENDO', 'FINALIZADO'),
               existing_nullable=True)

    # ### end Alembic commands ###
